id: I7FB4F972
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:01:00.979263
last_modified: 2023-02-08 15:01:00.979368
source_metadata:
  title: 'BA: Daśabhūmikasūtra'
  language: zh
bases:
  9F6F:
    base_file: 9F6F.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
